### PR TITLE
Remove Array.find from Store.jsx

### PR DESCRIPTION
**Pull request by taurheim**
**What**:

Stop using Array.find()

**Why**:

This is the only usage of array.find in the repo, which blocks IE11 usage when used

**How**:

Use array.filter with a length check instead of array.find

**Checklist**:

- [ ] Documentation added/updated
- [ ] Typescript definitions updated
- [ ] Tests added and passing
- [x] Ready to be merged

### CODE REVIEW

**Comment by tim-steele** [comment]
@taurheim interesting. 

So I get your point - but I don't think this is a 1-for-1 replacement. Array.find() returns the value of the first element it finds, Array.filter() will continue through the entire list.

This only becomes a problem on large carousels, and if the last image is still loading, then `find()` is no better than `filter()`. I am not against making this change.

Our of curiosity - Is this the only thing preventing IE11 usage?

**Comment by taurheim** [comment]
So far it seems that is the case, yes :) In my experience the big gotchas in IE are:
[Array.includes](https://caniuse.com/array-includes) (not used in this library)
[Array.find](https://caniuse.com/array-find) (only used here)
[Promise](https://caniuse.com/promises) (generally handled by transpiler)
[Fetch](https://caniuse.com/fetch) (not used in this library)
[Custom events](https://caniuse.com/customevent) (not used in this library)
[URLSearchParams](https://caniuse.com/urlsearchparams) (not used in this library)

Good point that it's not a 1 for 1 change - I can make this a loop that breaks out on first item as well for performance if it's a concern

**Comment by tim-steele** [comment]
@taurheim I don't think it is a concern. I would be curious if this would work in IE11 after this change was made.

**Pull request merged**
