### PR TITLE
Add types from WithStoreInterface for supporting Functional Components

### PR DESCRIPTION
**Pull request by cbasJS**
Finally I found the solution for the next issue.

e.g.
`interface Properties extends CarouselInjectedProps { }`
`const Anything: React.FC<Properties> = (props) => <div />`
`export const AnythingWithCarouselStore = WithStore<Properties>(Anything)`

While I'm trying to make something like that TypeScript throws the next error:

_Argument of type 'FC' is not assignable to parameter of type 'ComponentClass<Properties, any>'.
Type 'FunctionComponent' provides no match for the signature 'new (props: Properties, context?: any): Component<Properties, any, any>'._

So in this commit I've solved this one and now the WithStore module supports FunctionalComponents

I leave some examples below

### CODE REVIEW

**Comment by cbasJS** [comment]
`// Both with MapStateToProps and custom props`

`interface CustomProps extends CarouselInjectedProps {}`
`interface CarouselState { readonly currentSlide: number }`

` const InjectedFC: React.FC<CustomProps & CarouselState> = React.forwardRef((props, refs) => { `
  `useEffect(() => { props.carouselStore.setStoreState({ currentSlide: 2 }) }, []) `
  `return <div />`
`})`

`class InjectedCC extends React.Component<CustomProps & CarouselState> {`
`  componentDidMount() { this.props.carouselStore.setStoreState({ currentSlide: 2 }) }`
`  render() {`
`    return <div />`
  }
}

`const DecoratedCC = WithStore<CustomProps, CarouselState>(InjectedCC, (state) => ({ currentSlide: state.currentSlide }))`

`const DecoratedFC = WithStore<CustomProps, CarouselState>(InjectedFC, (state) => ({ currentSlide: state.currentSlide }))`

**Comment by cbasJS** [comment]
> No MapStateToProps

`interface CustomProps extends CarouselInjectedProps { name: string }`

`const InjectedFC: React.FC<CustomProps> = React.forwardRef((props: CustomProps, refs) => {`
`	useEffect(() => { props.carouselStore.setStoreState({ currentSlide: 2 }) }, []) `
`	return <div />`
`})`

`class InjectedCC extends React.Component<CustomProps> {`
`	componentDidMount() { this.props.carouselStore.setStoreState({ currentSlide: 2 }) }`
`	render() {`
`		return <div />`
`	}`
`}`

`const DecoratedCC = WithStore<CustomProps>(InjectedCC)`

`const DecoratedFC = WithStore<CustomProps>(InjectedFC)`

**Comment by tim-steele** [comment]
@cbasJS sorry for the delay on this - jumping on this now.

I have limited knowledge of TypeScript, but my understanding is you are allowing `withStoreInterface` to accept either a React Class Component or a React Functional Component (`React.FC`). Do I have this right?

**Comment by cbasJS** [comment]
> @cbasJS sorry for the delay on this - jumping on this now.
> 
> I have limited knowledge of TypeScript, but my understanding is you are allowing `withStoreInterface` to accept either a React Class Component or a React Functional Component (`React.FC`). Do I have this right?

@tim-steele No worries. Things happen!

Yeah, that's right. I updated some lines for supporting React.FC. =)

**Pull request closed without merging**
