### PR TITLE
Feature/Add TypeScript support

### PR DESCRIPTION
**Pull request by TheFullResolution**
I followed mostly your documentation, and double checked it with source code.

Types are mostly about props, and components available for users: I did not create types for Spinner, Stire, and helpers. Types will also not prevent users from not wrapping components with CarouselProvider (I omitted props passed by CarouselProvider), hopefully, they will follow the documentation 😄 

I tested types at a project I am working on at work and typescript complies without any issues. 

I am following your repository so in case of any issues I will get a notification and will try to fix the types as soon as possible.

### CODE REVIEW

**Comment by mrbinky3000** [comment]
@TheFullResolution  Hey, can you take a look at the new version of pure-react-carousel I just released and verify that the typescript support in this PR isThe new version is new version is v1.10.0

**Comment by TheFullResolution** [comment]
@mrbinky3000 Sure! I will update the typings. WithStore will take a while though... Those type of components is never easy to type.

**Comment by mrbinky3000** [comment]
Are HOC's hard to type because they are a function that returns a class?  I can move the class outside of the function if that helps.  I have done so on other projects to facilitate testing.  I don't know why every HOC I've seen puts the class in the function.  Seems weird to me, but it's done that way everywhere online.

**Comment by TheFullResolution** [comment]
I should manage, we have few strictly typed HOC at work and I have two senior devs who are very good with these. The trick is that now I will have to type the whole state and make sure WithStore types can be extended using generics (in case user also wants to pass custom props.)

Bottom line is: it is all doable but time-consuming if you want to do it right.

**Comment by TheFullResolution** [comment]
I am reopening the pull request! I added types for new WithStore. Again I tested the types on my work project and all seems to work. I have added also some information to README, including some examples. Types were heavily inspired by react-redux typings.

I think about adding some basic test in the near future to at least check if typescript compiles - incase people submit fixes.

**Pull request merged**
