### PR TITLE
Added disableDragStep flag to CarouselProvider

### PR DESCRIPTION
**Pull request by dominiby**
**What**: Added disableDragStep flag to CarouselProvider, in order to get the functionality of just the horizontal scroll, without any drag steps. As long as drag steps are great for desktop / tablet devices, on mobile a lot of users are used to just scrolling the content horizontally.  

**Why**: I need that functionality in the project. Furthermore, there was some Issue/Feature request regarding this (when I was first doing the research on it), but cannot find it now.

**How**: `disableDragStep` flag has been introduced on `CarouselProvider`, held in its state, that has default value of `false` and is passed to the `Slider` aswell. `Slider` uses the flag in `computeCurrentSlide`, passing it to `static slidesMoved` invocation. `slidesMoved` checks the passed value and either acts normally, or calculates proper position by dividing num of pixels dragged (`delta`) by width / height of the slide.

**Checklist**:

- [ ] Documentation added/updated
- [x] Typescript definitions updated
- [ ] Tests added and passing
- [ ] Ready to be merged 

I am opening the pull request first to see what you guys think. If it's something you would like to see and I get your approval, then I will go further with it and add tests, as well as update the documentation.
I've tried digging deep into the implementation and do not see any point where it could break the functionality (unless someone provides `dragStep` and `disableDragStep`... it's worth noting that the `dragStep` will not work in such a combination). All tests pass as usual. However, I might be missing something. Would really appreciate your feedback. 

I am also wondering whether the name of this flag `disableDragStep` is really proper here, maybe it should be renamed to `disableAutoDrag` or `disableAutoAdjust` or something, since it doesn't only make `dragStep` prop disabled, but it also won't adjust when there is a small drag, not a big drag (see `slidesMoved` implementation).

Btw. thank you very much for creating this library! We use it all the time now and it works like a charm :)

### CODE REVIEW

**Comment by dominiby** [comment]
Could anyone from maintainers take a look at it?

**Comment by tim-steele** [comment]
@dominiby are you just looking at doing a horizontal scroll vs. drag-to-next-slide?

**Comment by dominiby** [comment]
> @dominiby are you just looking at doing a horizontal scroll vs. drag-to-next-slide?

Yeah, I was just looking to have a simple horizontal-scroll feature, that would be especially useful on mobile devices, as a lot of apps tend to use it nowadays. I've forked the repo with that change and use the package based on my repo for now, but maybe it is something the users of the library might wanna see introduced.

**Comment by tim-steele** [comment]
@dominiby Okay - so I get what you are doing/asking. You aren't adding horizontal scrolling, but basically getting rid of the threshold that automatically takes the user to the next slide. Yes your code looks fine. If you want to

**Comment by mrbinky3000** [comment]
@dominiby if you want a simple horizontal scroll then why even use Pure React Carousel? Just do this instead.  I don't think the disable-drag-step feature belongs in our carousel.

https://codeburst.io/how-to-create-horizontal-scrolling-containers-d8069651e9c6

**Review by mrbinky3000 — CHANGES_REQUESTED** [review]
Can you provide a video of how the carousel behaves with this functionality.  If you just want a horizontal scrolling div, you don't need to use Pure React Carousel, you could just do the following: https://codeburst.io/how-to-create-horizontal-scrolling-containers-d8069651e9c6

**Comment by tim-steele** [comment]
@mrbinky3000 I think what this does is what is being requested here: https://github.com/express-labs/pure-react-carousel/issues/86

It removes the automated snap on drag. Correct @dominiby ? If this does, I think it would be a good PR.

**Comment by tim-steele** [comment]
@dominiby after a quick regroup - I think the question (and why @mrbinky3000 is asking for a video, etc.) is how does this impact the next/prev functionality? If you are dragged and halfway between two slides and hit next/prev does it take you one full slide width? Does it take you to the next/prev step?

**Pull request closed without merging**
