### PR TITLE
bugfix/role-update Remove unnecessary role from Slides.jsx

### PR DESCRIPTION
**Pull request by bluSCALE4**
Fix for #112

### CODE REVIEW

**Comment by mrbinky3000** [comment]
Thanks!  I was actually making a PR to do this and a few other things.   You beat me to it!

**Comment by mrbinky3000** [comment]
Wait... removing role="listbox" breaks aria rules requiring that interactive elements have a role.  Our carousel responds to keyboard events, so it requires a role.

https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-static-element-interactions.md

This might be fine for bootstrap, but we need a role.  It might be better to add the aria-option tag to the Slide component.

**Comment by bluSCALE4** [comment]
As mentioned on the bootstrap thread, listbox/option is more akin to a select box so informing a screen reader that this widget is a select box does more harm than good. Unfortunately, `role="widget"` isn't valid here so my thought is could we just squelch the error entirely? The example also referenced in the Bootstrap thread, https://www.w3.org/WAI/tutorials/carousels/working-example/, doesn't assign any roles in the element with listeners.

**Comment by mrbinky3000** [comment]
Re-opening.  Still working on this.

**Comment by tim-steele** [comment]
@bluSCALE4 we have read a lot of information, and talked to some internal accessibility resources.

There does not seem to be a "best" option for Carousel behavior using Aria. People have made an argument that you should use listbox, and that is what is being used in other accessibility components. People have made an argument that tablist is a better option. Others have made the argument that you can use marquee. There are reasons for and against each.

What is important is the use of the aria `role` attribute. This lets screen readers know that it is an interactive element. So we _do_ want to keep the attribute. We would be open to discussing whether there is a better role other than listbox, but we definitely don't want to remove the aria role completely.

**Pull request closed without merging**
