### PR TITLE
Closes #269 : make dot children prop optional

### LINKED ISSUE #269: Make children in <Dot /> not required
**Describe the feature you'd like:**

Currently the <Dot> Component is requiring the property`children`. However if your approach is to style the dots based on the dots markup only, you actual don't need any content.

Current workaround is something like: `<Dot><></></Dot>` or similiar

**Suggested implementation:**
Remove the requirement. Maybe adapt the Dot component.

**Describe alternatives you've considered:**
...

**Teachability, Documentation, Adoption, Migration Strategy:**
...

### PR DESCRIPTION
**Pull request by zhongdeliu**
**What**:

Made children of Dot component optional

**Why**:

See issue #269 - when using Dot directly, there may no need to have any children

**How**:

Changed props and updated docs (hopefully :) )

**Checklist**:

- [x] Documentation added/updated
- [x] Typescript definitions updated (
- [x] Tests added and passing
- [x] Ready to be merged

### CODE REVIEW

**Comment by zhongdeliu** [comment]
.

**Comment by zhongdeliu** [comment]
.

**Comment by zhongdeliu** [comment]
pretty disappointing...

**Comment by tim-steele** [comment]
@zhongdeliu why would we make this optional? Wouldn't we just exclude the dots?

**Comment by zhongdeliu** [comment]
@tim-steele for our use case we wanted the dots, but the <button> with the .dot class was totally sufficient. 
So is the intention to make the children prop optional

**Review by tim-steele — APPROVED** [review]

**Comment by tim-steele** [comment]
@allcontributors please add @zhongdeliu for code

**Pull request merged**
