### PR TITLE
Updates for React.StrictMode compliance

### PR DESCRIPTION
**Pull request by shoeman22**
**What**:
When used within a `<React.StrictMode />` block, this library was generating warnings since it was using the Legacy Context API.  This PR updates `CarouselProvider` and `WithStore` to use the New Context API as [recommended](https://reactjs.org/docs/strict-mode.html) by react.

There was also another strict mode warning with regard to using setState firing on an unmounted component, so I moved the subscribe step in the `Wrapper` component in `WithStore` to `componentDidMount()` to correct this warning.

**Why**:
I want to try out [Concurrent Mode](https://reactjs.org/docs/concurrent-mode-intro.html) and the React team recommends making sure your app works without warnings when in Strict Mode before giving it a go.  This library was the last hiccup I needed to solve to be warning free.

**How**:
I forked the repo and made the changes.

**Checklist**:

- [ ] Documentation added/updated (N/A)
- [ ] Typescript definitions updated (N/A)
- [x] Tests added and passing (N/A)
- [x] Ready to be merged 

Loving the library so far.  Great work!

### CODE REVIEW

**Comment by mrbinky3000** [comment]
Thanks very much for doing this.  However two tests are failing.

**Comment by bcarroll22** [comment]
Awesome, thanks @shoeman22! 

@allcontributors, please add @shoeman22 for code.

**Comment by shoeman22** [comment]
@mrbinky3000 @bcarroll22  ok, I updated the CarouselProvider to accommodate test properly.  Sorry for the noise in the commits -- I'd pushed to my own fork with `dist` in it so I could reference in package.json locally.

Thanks for the shoutout on the contributors as well!

**Comment by tim-steele** [comment]
@allcontributors, please add @shoeman22 for code.

**Pull request merged**
