### PR TITLE
fix(Slider): do not pass infinite to div

### PR DESCRIPTION
**Pull request by CarsonF**
**What**:
Not pass `infinite` prop to `div`

**Why**:
It's not a valid prop

**How**:
By destructing it out

**Checklist**:

- [ ] ~Documentation added/updated~ (N/A)
- [ ] ~Typescript definitions updated~ (N/A)
- [x] Tests added and passing
- [x] Ready to be merged 

Introduced with #204

### CODE REVIEW

**Comment by bcarroll22** [comment]
Thanks! @allcontributors, please add @CarsonF for code

**Comment by bcarroll22** [comment]
Also, @allcontributors add @nicksrandall for review

**Comment by CarsonF** [comment]
@bcarroll22 Thanks man. Any chance I could get a patch release?

**Comment by bcarroll22** [comment]
@tim-steele or @mrbinky3000 can we get a patch release for @CarsonF?

**Pull request merged**
